version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    container_name: meu_servidor_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
